// ============================================================================
// PREMIUM RESUME TEMPLATE LIBRARY — Curated Premium recruiter-approved Designs
// ============================================================================

export const CATEGORY_GROUPS = [
  { id: 'all', label: 'All Templates', categories: [] }
];

export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'All Templates' },
  { id: 'ats', label: 'ATS Friendly' },
  { id: 'professional', label: 'Professional' },
  { id: 'executive', label: 'Executive' },
  { id: 'technical', label: 'Technical' },
  { id: 'beginner', label: 'Beginner' }
];

// Curated 15 Premium Templates
export const TEMPLATES = [
  {
    id: 'ats-001',
    name: 'The Harvard',
    archetype: 'ats-optimized',
    categories: ['ats', 'professional'],
    category: 'ats',
    styles: {
      layout: 'single-column',
      headerType: 'centered',
      fontFamily: "'Crimson Text', serif",
      secondaryFont: "'Inter', sans-serif",
      headerColor: '#0f172a',
      accentColor: '#1e40af',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      sidebarBg: '#f8fafc',
      dividerStyle: 'thin-line',
      spacingScale: 1.0,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'tech-001',
    name: 'Silicon Valley',
    archetype: 'modern-sidebar',
    categories: ['technical', 'ats'],
    category: 'technical',
    styles: {
      layout: 'sidebar-left',
      headerType: 'classic',
      fontFamily: "'Inter', sans-serif",
      secondaryFont: "'Inter', sans-serif",
      headerColor: '#0f172a',
      accentColor: '#2563eb',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      sidebarBg: '#f8fafc',
      dividerStyle: 'accent-bar',
      spacingScale: 1.0,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'prof-001',
    name: 'The London',
    archetype: 'classic-clean',
    categories: ['professional', 'executive'],
    category: 'professional',
    styles: {
      layout: 'single-column',
      headerType: 'modern-split',
      fontFamily: "'Playfair Display', serif",
      secondaryFont: "'Roboto', sans-serif",
      headerColor: '#1c1917',
      accentColor: '#0f766e',
      backgroundColor: '#ffffff',
      textColor: '#374151',
      sidebarBg: '#f0fdfa',
      dividerStyle: 'double-line',
      spacingScale: 1.1,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'ats-002',
    name: 'Minimal ATS',
    archetype: 'ats-optimized',
    categories: ['ats', 'beginner'],
    category: 'ats',
    styles: {
      layout: 'single-column',
      headerType: 'classic',
      fontFamily: "'Roboto', sans-serif",
      secondaryFont: "'Roboto', sans-serif",
      headerColor: '#000000',
      accentColor: '#374151',
      backgroundColor: '#ffffff',
      textColor: '#111827',
      sidebarBg: '#f9fafb',
      dividerStyle: 'none',
      spacingScale: 0.95,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'beg-001',
    name: 'Creative Designer',
    archetype: 'modern-sidebar-right',
    categories: ['beginner', 'technical'],
    category: 'beginner',
    styles: {
      layout: 'sidebar-right',
      headerType: 'modern-split',
      fontFamily: "'Poppins', sans-serif",
      secondaryFont: "'Poppins', sans-serif",
      headerColor: '#292524',
      accentColor: '#e11d48',
      backgroundColor: '#ffffff',
      textColor: '#44403c',
      sidebarBg: '#fff1f2',
      dividerStyle: 'colored-block',
      spacingScale: 1.05,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'exec-001',
    name: 'Executive Director',
    archetype: 'executive-banner',
    categories: ['executive', 'professional'],
    category: 'executive',
    styles: {
      layout: 'single-column',
      headerType: 'modern-banner',
      fontFamily: "'Outfit', sans-serif",
      secondaryFont: "'Outfit', sans-serif",
      headerColor: '#1e3a5f',
      accentColor: '#b87333',
      backgroundColor: '#ffffff',
      textColor: '#334155',
      sidebarBg: '#fef3e2',
      dividerStyle: 'thick-line',
      spacingScale: 1.15,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'prof-002',
    name: 'The Oxford',
    archetype: 'academic-classic',
    categories: ['professional'],
    category: 'professional',
    styles: {
      layout: 'single-column',
      headerType: 'centered',
      fontFamily: "'Merriweather', serif",
      secondaryFont: "'Inter', sans-serif",
      headerColor: '#0c0a09',
      accentColor: '#475569',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      sidebarBg: '#f8fafc',
      dividerStyle: 'ornament',
      spacingScale: 1.1,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'tech-002',
    name: 'Modern Tech',
    archetype: 'modern-sidebar',
    categories: ['technical', 'professional'],
    category: 'technical',
    styles: {
      layout: 'sidebar-left',
      headerType: 'modern-banner',
      fontFamily: "'Inter', sans-serif",
      secondaryFont: "'Inter', sans-serif",
      headerColor: '#0f172a',
      accentColor: '#0284c7',
      backgroundColor: '#ffffff',
      textColor: '#334155',
      sidebarBg: '#e0f2fe',
      dividerStyle: 'accent-bar',
      spacingScale: 1.0,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'exec-002',
    name: 'Global Manager',
    archetype: 'corporate-grid',
    categories: ['executive', 'professional'],
    category: 'executive',
    styles: {
      layout: 'grid-layout',
      headerType: 'classic',
      fontFamily: "'DM Sans', sans-serif",
      secondaryFont: "'DM Sans', sans-serif",
      headerColor: '#1c1917',
      accentColor: '#0f766e',
      backgroundColor: '#ffffff',
      textColor: '#374151',
      sidebarBg: '#f0fdfa',
      dividerStyle: 'colored-block',
      spacingScale: 1.05,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'beg-002',
    name: 'The Geneva',
    archetype: 'two-column-balanced',
    categories: ['beginner', 'professional'],
    category: 'beginner',
    styles: {
      layout: 'two-column',
      headerType: 'centered',
      fontFamily: "'Lato', sans-serif",
      secondaryFont: "'Lato', sans-serif",
      headerColor: '#0f172a',
      accentColor: '#1e40af',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      sidebarBg: '#f8fafc',
      dividerStyle: 'thin-line',
      spacingScale: 1.0,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'tech-003',
    name: 'Creative Timeline',
    archetype: 'creative-timeline',
    categories: ['technical', 'beginner'],
    category: 'technical',
    styles: {
      layout: 'timeline',
      headerType: 'modern-banner',
      fontFamily: "'Raleway', sans-serif",
      secondaryFont: "'Raleway', sans-serif",
      headerColor: '#312e81',
      accentColor: '#6d28d9',
      backgroundColor: '#ffffff',
      textColor: '#3730a3',
      sidebarBg: '#ede9fe',
      dividerStyle: 'gradient-line',
      spacingScale: 1.05,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'ats-003',
    name: 'Corporate Prime',
    archetype: 'ats-optimized',
    categories: ['ats', 'professional'],
    category: 'ats',
    styles: {
      layout: 'single-column',
      headerType: 'classic',
      fontFamily: "'Inter', sans-serif",
      secondaryFont: "'Inter', sans-serif",
      headerColor: '#0f172a',
      accentColor: '#1e40af',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      sidebarBg: '#f0f4ff',
      dividerStyle: 'thick-line',
      spacingScale: 1.0,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'beg-003',
    name: 'Simple Fresher',
    archetype: 'ats-optimized',
    categories: ['beginner', 'ats'],
    category: 'beginner',
    styles: {
      layout: 'single-column',
      headerType: 'classic',
      fontFamily: "'Source Sans 3', sans-serif",
      secondaryFont: "'Source Sans 3', sans-serif",
      headerColor: '#14532d',
      accentColor: '#16a34a',
      backgroundColor: '#ffffff',
      textColor: '#374151',
      sidebarBg: '#f0fdf4',
      dividerStyle: 'thin-line',
      spacingScale: 0.95,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'exec-003',
    name: 'The Paris',
    archetype: 'elegant-divider',
    categories: ['executive'],
    category: 'executive',
    styles: {
      layout: 'single-column',
      headerType: 'centered',
      fontFamily: "'Playfair Display', serif",
      secondaryFont: "'Roboto', sans-serif",
      headerColor: '#450a0a',
      accentColor: '#b45309',
      backgroundColor: '#ffffff',
      textColor: '#404040',
      sidebarBg: '#fffbeb',
      dividerStyle: 'ornament',
      spacingScale: 1.15,
      sectionOrder: 'standard',
    }
  },
  {
    id: 'tech-004',
    name: 'Technical Lead',
    archetype: 'two-column-weighted',
    categories: ['technical', 'executive'],
    category: 'technical',
    styles: {
      layout: 'two-column',
      headerType: 'modern-split',
      fontFamily: "'Outfit', sans-serif",
      secondaryFont: "'Outfit', sans-serif",
      headerColor: '#0a0a0a',
      accentColor: '#d97706',
      backgroundColor: '#ffffff',
      textColor: '#171717',
      sidebarBg: '#fefce8',
      dividerStyle: 'gradient-line',
      spacingScale: 1.05,
      sectionOrder: 'standard',
    }
  }
];

export const PREMIUM_SAMPLE_DATA = {
  personal: {
    name: 'Alexandra Chen',
    role: 'Senior Software Engineer',
    email: 'alex.chen@email.com',
    phone: '+1 (415) 892-3047',
    location: 'San Francisco, CA',
    website: 'alexchen.dev',
    linkedin: 'linkedin.com/in/alexandrachen',
  },
  summary: 'Results-driven Senior Software Engineer with 8+ years of experience designing scalable distributed systems and leading cross-functional engineering teams. Specialized in cloud-native architectures, real-time data pipelines, and high-performance APIs serving 50M+ daily requests. Proven track record of reducing infrastructure costs by 40% while improving system reliability to 99.99% uptime.',
  experience: [
    {
      id: 1,
      role: 'Senior Software Engineer',
      company: 'Stripe',
      dates: 'Jan 2022 – Present',
      location: 'San Francisco, CA',
      description: '- Architected a real-time fraud detection pipeline processing 15M+ transactions daily with sub-100ms latency.\n- Led migration of monolithic payment service to microservices, reducing deployment time from 4 hours to 12 minutes.\n- Mentored 6 junior engineers and established code review standards adopted across 3 engineering teams.',
    },
    {
      id: 2,
      role: 'Software Engineer II',
      company: 'Datadog',
      dates: 'Jun 2019 – Dec 2021',
      location: 'New York, NY',
      description: '- Built high-throughput metrics ingestion service handling 2B+ data points per day using Go and Kafka.\n- Designed and implemented customer-facing dashboard API, improving page load performance by 65%.\n- Contributed to open-source monitoring libraries with 2,000+ GitHub stars.',
    },
    {
      id: 3,
      role: 'Software Engineer',
      company: 'Palantir Technologies',
      dates: 'Aug 2016 – May 2019',
      location: 'Palo Alto, CA',
      description: '- Developed data integration platform connecting 50+ enterprise data sources for Fortune 500 clients.\n- Optimized query engine reducing average response time from 8s to 400ms for complex analytical queries.',
    },
  ],
  education: [
    {
      id: 4,
      degree: 'M.S. Computer Science',
      school: 'Stanford University',
      dates: '2014 – 2016',
      honors: 'Focus: Distributed Systems & Machine Learning | GPA: 3.92/4.0',
    },
    {
      id: 5,
      degree: 'B.S. Computer Science',
      school: 'UC Berkeley',
      dates: '2010 – 2014',
      honors: 'Summa Cum Laude | Dean\'s List (all semesters) | GPA: 3.95/4.0',
    },
  ],
  skills: [
    { id: 6, category: 'Languages', items: 'Go, Python, TypeScript, Rust, Java, SQL' },
    { id: 7, category: 'Frameworks & Tools', items: 'React, Node.js, gRPC, Kafka, Redis, PostgreSQL' },
    { id: 8, category: 'Infrastructure', items: 'AWS, GCP, Kubernetes, Docker, Terraform, CI/CD' },
  ],
  projects: [
    {
      id: 9,
      name: 'DistCache — Distributed Caching Engine',
      link: 'github.com/alexchen/distcache',
      description: '- Built an open-source distributed memory cache in Go, achieving 50K ops/sec with consistent hashing.\n- Adopted by 3 companies in production; 1,200+ GitHub stars.',
    },
  ],
  certifications: [
    { id: 10, name: 'AWS Certified Solutions Architect – Professional', year: '2023' },
    { id: 11, name: 'Google Cloud Professional Data Engineer', year: '2022' },
  ],
  achievements: [
    { id: 12, name: 'Patent Holder — US Patent #10,234,567', details: 'Real-time anomaly detection in distributed payment systems' },
    { id: 13, name: '1st Place, Stripe Internal Hackathon 2023', details: 'Built ML-powered merchant risk scoring prototype' },
  ],
  languages: [
    { id: 14, name: 'English', proficiency: 'Native' },
    { id: 15, name: 'Mandarin', proficiency: 'Fluent' },
    { id: 16, name: 'Spanish', proficiency: 'Conversational' },
  ],
  customSections: [],
  visibleSections: {
    summary: true,
    experience: true,
    internships: false,
    education: true,
    skills: true,
    projects: true,
    certifications: true,
    achievements: true,
    languages: true,
    customSections: false,
  },
};
